### ISSUE TITLE
small questions

### ISSUE THREAD

**Issue by cocodrino** [JasonShin/reason-vue#3]
Hi @JasonShin  how're you??? I'm interested on reasonML (sicerally I just found this) but right now I'm working with nuxtjs developing universal apps (server rendering apps) checking your code seems than would be possible embedded reason code in vue files, which is pretty interesting for me...

my questions are...what is the status about this??? are you using right now???
would be possible integrate this with nuxt???

thank you

**Comment by JasonShin** [comment]
@cocodrino 
Hey, I'm doing good. At the moment I don't any plans on integrating nuxt.js into reason-vue. I believe once the initial reason-vue MVP is complete, you can drop in nuxt.js reason binding and it should just work.

**Comment by cocodrino** [comment]
thank you Jason, this looks really promising, I'll be alert...
